### ISSUE TITLE
After close the Incognito window, open website again, website can not recall anything

### ISSUE THREAD

**Issue by fishman1986** [MadhavBahlMD/Think-Incognito#5]

**Comment by MadhavBahl** [comment]
@fishman1986 it is working fine, please check again.
If it still doesnt work, can provide screenshots here?

![image](https://user-images.githubusercontent.com/26179770/34879332-e1664992-f7d2-11e7-89a7-1c01d1cf9711.png)
![image](https://user-images.githubusercontent.com/26179770/34879359-f8443566-f7d2-11e7-9ae1-f439cd5b892a.png)

**Comment by MadhavBahl** [comment]
@fishman1986after checking again, if you think this issue is resolved, please close it

**Comment by MadhavBahl** [comment]
There is no such issue, works fine.
I am closing it.
